spring:
  application:
    name: bookstore

  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore_bd
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8083